# Generated by Django 3.2.7 on 2021-11-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfforms',
            name='Current_Date',
            field=models.CharField(max_length=100),
        ),
    ]
