# Generated by Django 3.2.7 on 2021-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_pdfforms_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfforms',
            name='mail_body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pdfforms',
            name='mail_to',
            field=models.CharField(default='nikhil.sharma@jobaaj.com', max_length=500),
        ),
        migrations.AddField(
            model_name='pdfforms',
            name='subject',
            field=models.CharField(default='blank', max_length=500),
        ),
        migrations.AlterField(
            model_name='pdfforms',
            name='Role',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pdfforms',
            name='job_Description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
