# Generated by Django 3.2.7 on 2021-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_auto_20211126_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfforms',
            name='job_Description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pdfforms',
            name='mail_body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
