# Generated by Django 3.2.7 on 2021-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_auto_20211201_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfforms',
            name='Experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
