# Generated by Django 3.2.9 on 2021-12-10 06:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_pdfforms_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfforms',
            name='job_Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
